name: Fantasia e Fetiche
favicon: null
layout_spectrum: 0.33288712590001523
typography_spectrum: 0.9767692135646939
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.08996208291500807
  lightness: 0.07735199853777885
  saturation: 0.5875882939435542
  rhythmicContrast: 0.18692615465261042
purpose: []
